name: security-check-secrets-manager
on:
  push:
    branches:
      - master
    paths:
      - environment-name/secrets-manager/region-name/**.tf
  workflow_dispatch:
jobs:
  sast-tftsec-secrets-manager:
    name: sast-tftsec-secrets-manager
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ./environment-name/secrets-manager/region-name
          additional_args: --concise-output
          soft_fail: true
          github_token: ${{ secrets.GHA_TOKEN }}
