name: security-check-iam
on:
  push:
    branches:
      - master
    paths:
      - environment-name/iam/**.tf
  workflow_dispatch:
jobs:
  sast-tftsec-iam:
    name: sast-tftsec-iam
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ./environment-name/iam
          additional_args: --concise-output
          soft_fail: true
          github_token: ${{ secrets.GHA_TOKEN }}
